# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63e3f42afd1eeb939bb09c0e5ea59190181a484a4e6f8201e3f47237edbafe9601d8a58b72ad4636e176c89c02628762efc6114f478e73e74129038e84a75ebb

test:
  secret_key_base: 7b02d59941250139569490c2657e69379262d929ac404fa8d66c9882a6f0da3a865a0d7409c07c1d4fa82c4bd61a1530c76bbcf06061ac0366c02b38715e519b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
